### ISSUE TITLE
Minor issue with decomposition example chapter 2

### ISSUE THREAD

**Issue by davidfurrer** [daneah/practices-of-the-python-pro#1]
https://github.com/daneah/practices-of-the-python-pro/blob/9f191d5949a8bc7abafa668fc572a66c41afcc2b/ch02/decomposition.py#L75-L84

## Issue

Function only works if you have at least 3 names. otherwise (e.g. if have only 2): 
'person1, and person2'

**Comment by daneah** [comment]
Thanks @davidfurrer, I'll make sure this ends up in the errata!

**Comment by daneah** [comment]
This has been captured in the new `errata.html` file here, which will also end up on the book's page on manning.com, and I've updated the code in `decomposition.py` to address it.
