### ISSUE TITLE
Bug in Ch2, rock_paper_scissors.py function

### ISSUE THREAD

**Issue by bluekeybo** [daneah/practices-of-the-python-pro#2]
The function `print_options()` should start the enumeration with 1 to match the choices (fixed code shown below), otherwise it's a bug.

```python
def print_options():
    print('\n'.join(f'({i}) {option.title()}' for i, option in enumerate(OPTIONS, 1)))
```

**Comment by daneah** [comment]
Good catch! Can you clarify whether this actually breaks anything, or just prints `(0)...(1)...(2)` instead of `(1)...(2)...(3)`?

**Comment by bluekeybo** [comment]
Well, it asks the user to choose using 0,1,2 but then in the code is subtracting 1 to the choice thinking the user was shown 1,2,3 which gives the wrong value.

**Comment by daneah** [comment]
Ah, thanks for the quick update. Will definitely get this fixed in the book errata and push a fix here soon—need to work out what that process looks like on my end! Thanks 😄

**Comment by bluekeybo** [comment]
Perfect! Thank you!
