### ISSUE TITLE
Issue in Ch04, timing.py

### ISSUE THREAD

**Issue by bluekeybo** [daneah/practices-of-the-python-pro#4]
The timing module by default executes the statement for 1 million times ([link](https://docs.python.org/3/library/timeit.html)): `timeit.timeit(stmt='pass', setup='pass', timer=<default timer>, number=1000000)`

So the output of this line in the timing.py module should be in `us` not `ms`: 
```python
result = timeit(setup=setup, stmt=statement)
print(f'Took an average of {result}ms')
```

**Comment by daneah** [comment]
[The docs](https://docs.python.org/3/library/timeit.html#timeit.Timer.timeit) say that the result is returned in _seconds_, so I’ll double check what’s expected here. Good catch either way.

**Comment by daneah** [comment]
This is wrong in two ways! 😰 

The `result` is returned in seconds, so both our proposed units are off. In addition, the result is the _total run time over the number of runs_, so in this case to be the average time/run it needs to be divided by 1M. Will definitely fix this up!

**Comment by bluekeybo** [comment]
Well as you're printing how long it took on average, and the `timeit` module runs 1M runs by default, that's why I fixed the print statement to use `us` not `ms`. That takes care of the 1M runs.

**Comment by daneah** [comment]
That makes the intent a little less clear, in my opinion, so I think it'd be best to update the code to do the averaging.

**Comment by bluekeybo** [comment]
Oh I agree. For clarity's sake, also use the actual loop count you want to run in the function call so there's no confusion with the default used.

**Comment by daneah** [comment]
@bluekeybo I've created an `errata.html` file in this repo that should include all the points you've made along with some from liveBook feedback. This should also eventually appear on the book's page on manning.com as well. Thanks for your help! Keep them coming as you find them.
